version: "3"
services:
  ui:
   build:
      context: ./ui
      dockerfile: Dockerfile
   ports:
    -  3000:3000
   container_name: mern_ui
   networks:
    -  mern-stack-net
   depends_on:
    - api
   restart: always
   stdin_open: true
   tty: true

  api:
   build:
      context: ./api
      dockerfile: Dockerfile
   ports:
     - 3080:3080
   container_name: mern_api
   networks:
     - mern-stack-net
   depends_on:
    - db
   restart: always
   environment:
    - MONGO_CONNECTION_STRING=mongodb://mern_db:27017/todos
  db:
    restart: always
    image: mongo
    ports:
      - 27017:27017
    container_name: mern_db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
