version: "3"
services:
  ui:
   build:
      context: ./ui
      dockerfile: Dockerfile
   ports:
    -  3000:3000
   container_name: todo_ui
   networks:
    -  mern-stack-net
   volumes:
    -  ./ui/src:/usr/app/src
    -  ./ui/public:/usr/app/public
   depends_on:
    - api
   restart: always
   stdin_open: true
   tty: true

  api:
   build:
      context: ./api
      dockerfile: Dockerfile
   ports:
     - 3080:3080
   container_name: todo_api
   networks:
     - mern-stack-net
   volumes:
    - ./api/src:/usr/app/src
   depends_on:
    - db
   restart: always
   environment:
    - MONGO_CONNECTION_STRING=mongodb+srv://Tester123:51FWAl9CFZuJe9xF@todo-cluster.dc3nz.mongodb.net/todos?retryWrites=true&w=majority
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: todo_db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
